name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the repository's code
      - name: Checkout code
        uses: actions/checkout@main

      # Set up AWS CLI
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@main
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1  # Specify your region here

      # List all S3 buckets
      - name: List all S3 Buckets
        run: |
          aws s3 ls

      # Check if the S3 bucket exists, create if not
      - name: Ensure S3 Bucket Exists
        run: |
          BUCKET_NAME="mohd-github"
          if ! aws s3 ls "s3://$BUCKET_NAME" 2>&1 | grep -q 'NoSuchBucket'; then
            echo "Bucket exists: $BUCKET_NAME"
          else
            echo "Bucket does not exist, creating: $BUCKET_NAME"
            aws s3 mb s3://$BUCKET_NAME
          fi

      # Upload a file to the existing or newly created S3 bucket
      - name: Upload file to S3
        run: |
          BUCKET_NAME="mohd-github"  # Explicitly set bucket name here
          echo "This is a sample file content" > index.html  # Create a sample file
          aws s3 cp index.html s3://$BUCKET_NAME/index.html  # Upload file to the bucket

      # Optionally, clean up the S3 bucket
      - name: Clean up S3 bucket
        run: |
          aws s3 rm s3://$BUCKET_NAME/index.html
          aws s3 rb s3://$BUCKET_NAME --force  # Remove bucket and its contents
